### ISSUE TITLE
Departments Page - Test Accounts

### ISSUE THREAD

**Issue by adabutch** [City-of-Bloomington/directory#34]
![Screen Shot 2019-08-22 at 8 48 19 AM](https://user-images.githubusercontent.com/2372040/63515792-a358a400-c4b9-11e9-8234-3fd9ce4d359e.png)

Let's not (?) publicly display **`Test Accounts`** created via Account Tracker (_+etc_) on the **`Departments`** page.

**Comment by inghamn** [comment]
The directory web application is a view of everything underneath "Departments" in ActiveDirectory.  Can we move the test accounts somewhere else?

**Comment by adabutch** [comment]
@sethCOB - 

> Can we move the test accounts somewhere else?

**FWIW:** When I'm back into the AT application, I'm totally fine switching the setup to flow w. whatever change is applied here. Without actually checking, I believe these accounts above are likely from AT testing.

**Comment by inghamn** [comment]
We deleted the test accounts
